# Generated by Django 4.2.17 on 2024-12-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth_app', '0002_peopleinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='peopleinformation',
            name='institution',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='PeopleSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='ehealth_app.people')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='ehealth_app.socialplatform')),
            ],
        ),
        migrations.AddField(
            model_name='peopleinformation',
            name='research_interests',
            field=models.ManyToManyField(blank=True, to='ehealth_app.researchinterest'),
        ),
    ]
