# Generated by Django 4.2.17 on 2024-12-19 23:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth_app', '0007_membership_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
