# Generated by Django 4.2.17 on 2024-12-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth_app', '0008_alter_people_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='roleBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='people',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='people_images/'),
        ),
        migrations.AddField(
            model_name='peopleinformation',
            name='role_badge',
            field=models.ManyToManyField(blank=True, to='ehealth_app.rolebadge'),
        ),
    ]
