# Generated by Django 4.2.17 on 2024-12-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth_app', '0009_rolebadge_alter_people_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='title',
            field=models.CharField(blank=True, choices=[('', ''), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], default='', max_length=10),
        ),
    ]
