# Generated by Django 4.2.17 on 2024-12-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth_app', '0003_researchinterest_socialplatform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='peoplesociallink',
            unique_together={('people', 'platform', 'url')},
        ),
        migrations.AddField(
            model_name='peopleinformation',
            name='areas_of_expertise',
            field=models.ManyToManyField(blank=True, to='ehealth_app.areaofexpertise'),
        ),
    ]
