# Generated by Django 4.2.17 on 2025-02-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth_app', '0010_alter_people_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='title',
            field=models.CharField(blank=True, choices=[('', ''), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Assoc. Prof.', 'Assoc. Prof.'), ('Prof.', 'Prof.')], default='', max_length=20),
        ),
    ]
