# Generated by Django 4.2.17 on 2025-05-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth_app', '0012_fileupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='file',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='url',
            field=models.URLField(default='https://example.com'),
        ),
    ]
