# Generated by Django 4.2.17 on 2024-12-19 15:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_user', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehealth_app.people')),
            ],
        ),
    ]
